name: 'Test AOP Actions'
on: # rebuild any PRs and main branch changes
  
  workflow_dispatch:

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-on-packages/sample-action@1.0.0
        with:
          milliseconds: 1000
